source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Tunits_Example', :exclusive => true do
  pod "Tunits", :path => "../"
end

target 'Tunits_Tests', :exclusive => true do
  pod "Tunits", :path => "../"

  pod 'Quick' 
  pod 'Nimble', '2.0.0-rc.3'
end

post_install do |installer|
	installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
		configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
	end
end
